---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile_local.erb

provisioner:
  name: ansible_playbook
  hosts: apt-hosts
  sudo_command: sudo -E -H
  role_name: apt
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
# disabled omnibus and switched to pip install to workaround python-six related
# dependency issues on Ubuntu 14.04
  require_pip: true
  ansible_version: 2.3.0
  ansible_verbose: true
  ansible_verbosity: warn
  idempotency_test: true

verifier:
  name: shell

suites:
  - name: apt-all
    provisioner:
      playbook: tests/apt-all.yml
    verifier:
      command: PLAYBOOK=tests/apt-all.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-1404

  - name: apt-https
    provisioner:
      playbook: tests/apt-https.yml
    verifier:
      command: PLAYBOOK=tests/apt-https.yml bundle exec rspec -c -I serverspec

  - name: apt-s3
    provisioner:
      playbook: tests/apt-s3.yml
    verifier:
      command: PLAYBOOK=tests/apt-s3.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-1404

  - name: apt-spacewalk
    provisioner:
      playbook: tests/apt-spacewalk.yml
    verifier:
      command: PLAYBOOK=tests/apt-spacewalk.yml bundle exec rspec -c -I serverspec

  - name: apt-tor
    provisioner:
      playbook: tests/apt-tor.yml
    verifier:
      command: PLAYBOOK=tests/apt-tor.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-1404

  - name: sources-jessie
    provisioner:
      playbook: tests/sources-jessie.yml
    verifier:
      command: PLAYBOOK=tests/sources-jessie.yml bundle exec rspec -c -I serverspec
    excludes:
      - ubuntu-1404
      - ubuntu-1604

  - name: sources-trusty
    provisioner:
      playbook: tests/sources-trusty.yml
    verifier:
      command: PLAYBOOK=tests/sources-trusty.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-1604

  - name: sources-xenial
    provisioner:
      playbook: tests/sources-xenial.yml
    verifier:
      command: PLAYBOOK=tests/sources-xenial.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-1404

platforms:
  - name: debian-8
    driver_config:
      box: bento/debian-8.6
      box_url: https://atlas.hashicorp.com/bento/debian-8.6

  - name: ubuntu-1404
    driver_config:
      box: bento/ubuntu-14.04
      box_url: https://atlas.hashicorp.com/bento/ubuntu-14.04

  - name: ubuntu-1604
    driver_config:
      box: bento/ubuntu-16.04
      box_url: https://atlas.hashicorp.com/bento/ubuntu-16.04
