---

driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids: [ "<%= ENV['AWS_SGROUP_ID'] %>" ]
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  instance_type: <%= ENV['AWS_INSTANCE_TYPE'] || 't2.micro' %>
  associate_public_ip: true
  require_chef_omnibus: false
  tags:
    'ansible-role': ansible-role-apt
<% if ENV['AWS_SUBNET'] %>
  subnet_id: <%= ENV['AWS_SUBNET'] %>
<% end %>
<% if ENV['AWS_IAM_PROFILE'] %>
  iam_profile_name: <%= ENV['AWS_IAM_PROFILE'] %>
<% end %>

transport:
  ssh_key: <%= ENV['KITCHEN_SSH_KEY'] %>
  connection_timeout: 120
  connection_retries: 10
  max_ssh_sessions: 4

provisioner:
  name: ansible_playbook
  hosts: all
  role_name: apt
  sudo_command: sudo -E -H
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
# disabled omnibus and switched to pip install to workaround python-six related
# dependency issues on Ubuntu 14.04
  require_pip: true
  ansible_version: 2.3.0
  ansible_verbose: true
  ansible_verbosity: warn
  idempotency_test: true

verifier:
  name: shell

suites:
  - name: apt-all
    provisioner:
      playbook: tests/apt-all.yml
    verifier:
      command: PLAYBOOK=tests/apt-all.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-14.04

  - name: apt-https
    provisioner:
      playbook: tests/apt-https.yml
    verifier:
      command: PLAYBOOK=tests/apt-https.yml bundle exec rspec -c -I serverspec

  - name: apt-s3
    provisioner:
      playbook: tests/apt-s3.yml
    verifier:
      command: PLAYBOOK=tests/apt-s3.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-14.04

  - name: apt-spacewalk
    provisioner:
      playbook: tests/apt-spacewalk.yml
    verifier:
      command: PLAYBOOK=tests/apt-spacewalk.yml bundle exec rspec -c -I serverspec

  - name: apt-tor
    provisioner:
      playbook: tests/apt-tor.yml
    verifier:
      command: PLAYBOOK=tests/apt-tor.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-14.04

  - name: sources-jessie
    provisioner:
      playbook: tests/sources-jessie.yml
    verifier:
      command: PLAYBOOK=tests/sources-jessie.yml bundle exec rspec -c -I serverspec
    excludes:
      - ubuntu-14.04
      - ubuntu-16.04

  - name: sources-trusty
    provisioner:
      playbook: tests/sources-trusty.yml
    verifier:
      command: PLAYBOOK=tests/sources-trusty.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-16.04

  - name: sources-xenial
    provisioner:
      playbook: tests/sources-xenial.yml
    verifier:
      command: PLAYBOOK=tests/sources-xenial.yml bundle exec rspec -c -I serverspec
    excludes:
      - debian-8
      - ubuntu-14.04

platforms:
  - name: debian-8
  - name: ubuntu-14.04
  - name: ubuntu-16.04
